# api_platform:
#     mapping:
#         paths: ['%kernel.project_dir%/src/Entity']
#     title: Hello API Platform
#     version: 1.0.0
#     formats:
#         jsonld: ['application/ld+json']
#     docs_formats:
#         jsonld: ['application/ld+json']
#         jsonopenapi: ['application/vnd.openapi+json']
#         html: ['text/html']
#     defaults:
#         # DEV : Liaison API frontend Angular: 
#         attributes:
#                 cors:
#                     allow_origin: ['http://localhost:4200']
#                     allow_headers: ['content-type', 'authorization']
#                     allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
#                     max_age: 3600
#         stateless: true
#         cache_headers:
#             vary: ['Content-Type', 'Authorization', 'Origin']
#         extra_properties:
#             standard_put: true
#             rfc_7807_compliant_errors: true
#     keep_legacy_inflector: false
#     use_symfony_listeners: true


api_platform:
    title: Hello API Platform
    version: 1.0.0
    formats:
        jsonld: ['application/ld+json']
    docs_formats:
        jsonld: ['application/ld+json']
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
    event_listeners_backward_compatibility_layer: false
    keep_legacy_inflector: false
    eager_loading:
        max_joins: 100  # Increase this value as needed
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    # cors:
    #     allow_origin: ['http://localhost:3000']
    #     allow_headers: ['Content-Type']
    #     allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
